# Generated by Django 4.2.5 on 2023-09-21 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_nation', '0004_auto_20181004_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='uploaded_on',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 14, 59, 53, 113414)),
        ),
    ]
